//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Readability {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Readability.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///able
        ///aboard
        ///about
        ///above 
        ///absent 
        ///accept 
        ///accident 
        ///account 
        ///ache 
        ///aching 
        ///acorn 
        ///acre 
        ///across 
        ///act 
        ///acts 
        ///add 
        ///address 
        ///admire 
        ///adventure 
        ///afar 
        ///afraid
        ///after 
        ///afternoon 
        ///afterward 
        ///afterwards 
        ///again 
        ///against
        ///age 
        ///aged 
        ///ago 
        ///agree 
        ///ah 
        ///ahead 
        ///aid 
        ///aim 
        ///air 
        ///airfield 
        ///airplane 
        ///airport 
        ///airship 
        ///airy 
        ///alarm 
        ///alike 
        ///alive 
        ///all 
        ///alley 
        ///alligator 
        ///allow 
        ///almost 
        ///alone 
        ///along 
        ///aloud
        ///already
        ///also
        ///always
        ///am
        ///America
        ///American
        ///among
        ///amount
        ///an
        ///and
        ///angel
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChallEasyWords {
            get {
                return ResourceManager.GetString("ChallEasyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///able
        ///acy
        ///al
        ///ance
        ///ate
        ///dom
        ///en
        ///ence
        ///er
        ///es
        ///esque
        ///ful
        ///fy
        ///ible
        ///ic
        ///ical
        ///ify
        ///ing
        ///ious
        ///ise
        ///ish
        ///ism
        ///ist
        ///ity
        ///ive
        ///ize
        ///less
        ///ly
        ///ment
        ///ness
        ///or
        ///ous
        ///s
        ///ship
        ///sion
        ///tion
        ///ty
        ///y.
        /// </summary>
        internal static string WordSuffixes {
            get {
                return ResourceManager.GetString("WordSuffixes", resourceCulture);
            }
        }
    }
}
